#guess random number generated by computer
import random


def guess(x):
    #generate random number between 1 and the number you call the function with
    random_number = random.randint(1, x)
    guess = 0
    while guess != random_number:
        guess = int(input(f"guess a number between 1 and {x}: "))
        if guess < random_number: 
            print("sorry, guess again too low")
        elif guess > random_number:
            print("sorry, guess again, number is too high")

    print(f"Yay, congrats. You have guessed the number {random_number} correctly")

#let computer guess random number generated by user
def computer_guess(x):
    low = 1
    high = x
    feedback = ''
    while feedback != 'c' and low != high:
        if low != high:
            guess = random.randint(low, high)
        else: 
            guess = low
        feedback = input(f"is {guess} higher (H), lower (L) or correct(C)? ").lower()
        if feedback == 'h':
            high = guess - 1
        elif feedback == 'l':
            low = guess - 1

    print('yay! The computer guessed your number, {guess}, correctly! ')




#guess(4)
computer_guess(100)